import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/layout/Header";
import AuthGuardProvider, { ProtectedRouteGate } from "@/components/auth/AuthGuardProvider";

const pretendard = localFont({
  variable: "--font-pretendard",
  src: [
    { path: "./fonts/pretendard/Pretendard-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/pretendard/Pretendard-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "./fonts/pretendard/Pretendard-Bold.woff2", weight: "700", style: "normal" },
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "AI-STOCK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <AuthGuardProvider>
          <Header />

          <ProtectedRouteGate>
            <div className="flex-1 flex flex-col">
              {children}
            </div>
          </ProtectedRouteGate>
        </AuthGuardProvider>
      </body>
    </html>
  );
}
