import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import AuthGuardProvider, { ProtectedRouteGate } from "@/components/auth/AuthGuardProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI-STOCK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <body className="min-h-screen flex flex-col">
        <AuthGuardProvider>
          <Header />

          <ProtectedRouteGate>
            <div className="flex-1 flex flex-col">
              {children}
            </div>
          </ProtectedRouteGate>
        </AuthGuardProvider>
      </body>
    </html>
  );
}
